export const stocks = [
    "Microsoft",
    "NVIDIA",
    "Apple",
    "Amazon",
    "Alphabet",
    "Meta Platforms",
    "Tesla",
    "Eli Lilly",
    "Walmart",
    "JPMorgan Chase",
    "Airbnb",
    "Visa",
    "Oracle",
    "Netflix",
    "Mastercard",
    "ExxonMobil",
    "Costco",
    "Johnson & Johnson",
    "Procter & Gamble",
    "Home Depot",
    "AbbVie",
    "Bank of America",
    "Palantir",
    "Coca-Cola",
    "Alibaba",
    "Novo Nordisk",
];

export const crypto = [
    "Bitcoin",
    "Ethereum",
    "Tether",
    "XRP",
    "BNB",
    "Solana",
    "USD Coin",
    "Tron",
    "Cardano",
    "Avalanche",
    "Dogecoin",
    "Polygon",
    "Polkadot",
    "Litecoin",
    "Shiba Inu",
];

export const etfs = [
    "Vanguard S&P 500 ETF",
    "Invesco QQQ Trust",
    "Vanguard Total Stock Market ETF",
    "iShares Russell 2000 ETF",
    "Vanguard Total World Stock ETF",
    "Vanguard FTSE Developed Markets ETF",
    "iShares Core MSCI Emerging Markets ETF",
    "ARK Innovation ETF",
];